name: audio_flutter
description: audio_flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_ffmpeg: ^0.2.8
  flutter_sound: ^1.8.0
  path_provider: ^1.5.0
  crypto: ^2.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
