name: asdasd
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ffmpeg: ^0.2.8
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.0
  flutter_plugin_record: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

