name: asdasd
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_ffmpeg: ^0.2.8
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.0
  flutter_plugin_record: ^0.1.2
  provider: ^3.2.0
  flutter_custom_calendar:
    git:
      url: https://github.com/LXD312569496/flutter_custom_calendar.git
  event_bus: ^1.1.0
  audioplayers: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true
  assets:
    - asset/
    - asset/edit/
    - asset/flag/
    - asset/home_recording/
    - asset/palying/
    - asset/setting/
    - asset/sheared/
    - asset/toolbar/



